### ISSUE TITLE
Work with shade plugin

### ISSUE THREAD

**Issue by pparth** [spring-attic/aws-maven#10]
Hello,
I use the shade plugin in order to create a fat, single executable jar with a specific name. This jar contains all my application and has a specific name. Is there a way to use the maven s3 plugin to upload just this jar? I don't mind uploading the md5 or sha1 files too but it seems that the jar generated by the shade plugin is not used at all.

QAlso, is there a way to upload to a specific folder in the S3 bucket and not one created using the package paths?

**Comment by nebhale** [comment]
This wagon simply slots into the standard Maven functionality.  That is, the files that are uploaded and the location that they are uploaded to are not determined by the wagon, but rather by Maven and then executed by the wagon.  Therefore, to control both the files that you want to upload and the location that you'd like to upload them to, you'll have to use Maven's configuration (not the Wagon's).

**Comment by pparth** [comment]
Thanks!

Do you have some insight on where to search for?

**Comment by nebhale** [comment]
You'll want to attach an artifact using the [build-helper:attach-artifact](http://mojo.codehaus.org/build-helper-maven-plugin/attach-artifact-mojo.html) plugin.  It is surprising to me that the shade plugin doesn't do this automatically though.  You'll probably want to open an issue with them to have the plugin automatically attach the artifact when the plugin runs rather than you attaching it manually.

As far as the directory that it uploads to, I've never successfully adjusted that value and I'm not sure it's possible.  Engaging with the Maven community on that one seems to be your best bet.
